with-expecter: true
packages:
    "github.com/go-ldap/ldap/v3":
        # place your package-specific config here
#        config:
        interfaces:
            # select the interfaces you want mocked
            Client:
                # Modify package-level config for this specific interface (if applicable)
#                config:
