// Code generated by mockery v2.33.2. DO NOT EDIT.

package ldap

import (
	ldap "github.com/go-ldap/ldap/v3"
	mock "github.com/stretchr/testify/mock"

	time "time"

	tls "crypto/tls"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0
func (_m *MockClient) Add(_a0 *ldap.AddRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.AddRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 *ldap.AddRequest
func (_e *MockClient_Expecter) Add(_a0 interface{}) *MockClient_Add_Call {
	return &MockClient_Add_Call{Call: _e.mock.On("Add", _a0)}
}

func (_c *MockClient_Add_Call) Run(run func(_a0 *ldap.AddRequest)) *MockClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.AddRequest))
	})
	return _c
}

func (_c *MockClient_Add_Call) Return(_a0 error) *MockClient_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Add_Call) RunAndReturn(run func(*ldap.AddRequest) error) *MockClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Bind provides a mock function with given fields: username, password
func (_m *MockClient) Bind(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Bind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bind'
type MockClient_Bind_Call struct {
	*mock.Call
}

// Bind is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockClient_Expecter) Bind(username interface{}, password interface{}) *MockClient_Bind_Call {
	return &MockClient_Bind_Call{Call: _e.mock.On("Bind", username, password)}
}

func (_c *MockClient_Bind_Call) Run(run func(username string, password string)) *MockClient_Bind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_Bind_Call) Return(_a0 error) *MockClient_Bind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Bind_Call) RunAndReturn(run func(string, string) error) *MockClient_Bind_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *MockClient) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Compare provides a mock function with given fields: dn, attribute, value
func (_m *MockClient) Compare(dn string, attribute string, value string) (bool, error) {
	ret := _m.Called(dn, attribute, value)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(dn, attribute, value)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(dn, attribute, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(dn, attribute, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockClient_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - dn string
//   - attribute string
//   - value string
func (_e *MockClient_Expecter) Compare(dn interface{}, attribute interface{}, value interface{}) *MockClient_Compare_Call {
	return &MockClient_Compare_Call{Call: _e.mock.On("Compare", dn, attribute, value)}
}

func (_c *MockClient_Compare_Call) Run(run func(dn string, attribute string, value string)) *MockClient_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_Compare_Call) Return(_a0 bool, _a1 error) *MockClient_Compare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Compare_Call) RunAndReturn(run func(string, string, string) (bool, error)) *MockClient_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function with given fields: _a0
func (_m *MockClient) Del(_a0 *ldap.DelRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.DelRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - _a0 *ldap.DelRequest
func (_e *MockClient_Expecter) Del(_a0 interface{}) *MockClient_Del_Call {
	return &MockClient_Del_Call{Call: _e.mock.On("Del", _a0)}
}

func (_c *MockClient_Del_Call) Run(run func(_a0 *ldap.DelRequest)) *MockClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.DelRequest))
	})
	return _c
}

func (_c *MockClient_Del_Call) Return(_a0 error) *MockClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Del_Call) RunAndReturn(run func(*ldap.DelRequest) error) *MockClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// DirSync provides a mock function with given fields: searchRequest, flags, maxAttrCount, cookie
func (_m *MockClient) DirSync(searchRequest *ldap.SearchRequest, flags int64, maxAttrCount int64, cookie []byte) (*ldap.SearchResult, error) {
	ret := _m.Called(searchRequest, flags, maxAttrCount, cookie)

	var r0 *ldap.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest, int64, int64, []byte) (*ldap.SearchResult, error)); ok {
		return rf(searchRequest, flags, maxAttrCount, cookie)
	}
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest, int64, int64, []byte) *ldap.SearchResult); ok {
		r0 = rf(searchRequest, flags, maxAttrCount, cookie)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.SearchRequest, int64, int64, []byte) error); ok {
		r1 = rf(searchRequest, flags, maxAttrCount, cookie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DirSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirSync'
type MockClient_DirSync_Call struct {
	*mock.Call
}

// DirSync is a helper method to define mock.On call
//   - searchRequest *ldap.SearchRequest
//   - flags int64
//   - maxAttrCount int64
//   - cookie []byte
func (_e *MockClient_Expecter) DirSync(searchRequest interface{}, flags interface{}, maxAttrCount interface{}, cookie interface{}) *MockClient_DirSync_Call {
	return &MockClient_DirSync_Call{Call: _e.mock.On("DirSync", searchRequest, flags, maxAttrCount, cookie)}
}

func (_c *MockClient_DirSync_Call) Run(run func(searchRequest *ldap.SearchRequest, flags int64, maxAttrCount int64, cookie []byte)) *MockClient_DirSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.SearchRequest), args[1].(int64), args[2].(int64), args[3].([]byte))
	})
	return _c
}

func (_c *MockClient_DirSync_Call) Return(_a0 *ldap.SearchResult, _a1 error) *MockClient_DirSync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DirSync_Call) RunAndReturn(run func(*ldap.SearchRequest, int64, int64, []byte) (*ldap.SearchResult, error)) *MockClient_DirSync_Call {
	_c.Call.Return(run)
	return _c
}

// ExternalBind provides a mock function with given fields:
func (_m *MockClient) ExternalBind() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ExternalBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExternalBind'
type MockClient_ExternalBind_Call struct {
	*mock.Call
}

// ExternalBind is a helper method to define mock.On call
func (_e *MockClient_Expecter) ExternalBind() *MockClient_ExternalBind_Call {
	return &MockClient_ExternalBind_Call{Call: _e.mock.On("ExternalBind")}
}

func (_c *MockClient_ExternalBind_Call) Run(run func()) *MockClient_ExternalBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ExternalBind_Call) Return(_a0 error) *MockClient_ExternalBind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ExternalBind_Call) RunAndReturn(run func() error) *MockClient_ExternalBind_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastError provides a mock function with given fields:
func (_m *MockClient) GetLastError() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_GetLastError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastError'
type MockClient_GetLastError_Call struct {
	*mock.Call
}

// GetLastError is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetLastError() *MockClient_GetLastError_Call {
	return &MockClient_GetLastError_Call{Call: _e.mock.On("GetLastError")}
}

func (_c *MockClient_GetLastError_Call) Run(run func()) *MockClient_GetLastError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetLastError_Call) Return(_a0 error) *MockClient_GetLastError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_GetLastError_Call) RunAndReturn(run func() error) *MockClient_GetLastError_Call {
	_c.Call.Return(run)
	return _c
}

// IsClosing provides a mock function with given fields:
func (_m *MockClient) IsClosing() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_IsClosing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosing'
type MockClient_IsClosing_Call struct {
	*mock.Call
}

// IsClosing is a helper method to define mock.On call
func (_e *MockClient_Expecter) IsClosing() *MockClient_IsClosing_Call {
	return &MockClient_IsClosing_Call{Call: _e.mock.On("IsClosing")}
}

func (_c *MockClient_IsClosing_Call) Run(run func()) *MockClient_IsClosing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_IsClosing_Call) Return(_a0 bool) *MockClient_IsClosing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_IsClosing_Call) RunAndReturn(run func() bool) *MockClient_IsClosing_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function with given fields: _a0
func (_m *MockClient) Modify(_a0 *ldap.ModifyRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.ModifyRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type MockClient_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - _a0 *ldap.ModifyRequest
func (_e *MockClient_Expecter) Modify(_a0 interface{}) *MockClient_Modify_Call {
	return &MockClient_Modify_Call{Call: _e.mock.On("Modify", _a0)}
}

func (_c *MockClient_Modify_Call) Run(run func(_a0 *ldap.ModifyRequest)) *MockClient_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.ModifyRequest))
	})
	return _c
}

func (_c *MockClient_Modify_Call) Return(_a0 error) *MockClient_Modify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Modify_Call) RunAndReturn(run func(*ldap.ModifyRequest) error) *MockClient_Modify_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyDN provides a mock function with given fields: _a0
func (_m *MockClient) ModifyDN(_a0 *ldap.ModifyDNRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ldap.ModifyDNRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ModifyDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyDN'
type MockClient_ModifyDN_Call struct {
	*mock.Call
}

// ModifyDN is a helper method to define mock.On call
//   - _a0 *ldap.ModifyDNRequest
func (_e *MockClient_Expecter) ModifyDN(_a0 interface{}) *MockClient_ModifyDN_Call {
	return &MockClient_ModifyDN_Call{Call: _e.mock.On("ModifyDN", _a0)}
}

func (_c *MockClient_ModifyDN_Call) Run(run func(_a0 *ldap.ModifyDNRequest)) *MockClient_ModifyDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.ModifyDNRequest))
	})
	return _c
}

func (_c *MockClient_ModifyDN_Call) Return(_a0 error) *MockClient_ModifyDN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ModifyDN_Call) RunAndReturn(run func(*ldap.ModifyDNRequest) error) *MockClient_ModifyDN_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyWithResult provides a mock function with given fields: _a0
func (_m *MockClient) ModifyWithResult(_a0 *ldap.ModifyRequest) (*ldap.ModifyResult, error) {
	ret := _m.Called(_a0)

	var r0 *ldap.ModifyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.ModifyRequest) (*ldap.ModifyResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ldap.ModifyRequest) *ldap.ModifyResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.ModifyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.ModifyRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ModifyWithResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyWithResult'
type MockClient_ModifyWithResult_Call struct {
	*mock.Call
}

// ModifyWithResult is a helper method to define mock.On call
//   - _a0 *ldap.ModifyRequest
func (_e *MockClient_Expecter) ModifyWithResult(_a0 interface{}) *MockClient_ModifyWithResult_Call {
	return &MockClient_ModifyWithResult_Call{Call: _e.mock.On("ModifyWithResult", _a0)}
}

func (_c *MockClient_ModifyWithResult_Call) Run(run func(_a0 *ldap.ModifyRequest)) *MockClient_ModifyWithResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.ModifyRequest))
	})
	return _c
}

func (_c *MockClient_ModifyWithResult_Call) Return(_a0 *ldap.ModifyResult, _a1 error) *MockClient_ModifyWithResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ModifyWithResult_Call) RunAndReturn(run func(*ldap.ModifyRequest) (*ldap.ModifyResult, error)) *MockClient_ModifyWithResult_Call {
	_c.Call.Return(run)
	return _c
}

// NTLMUnauthenticatedBind provides a mock function with given fields: domain, username
func (_m *MockClient) NTLMUnauthenticatedBind(domain string, username string) error {
	ret := _m.Called(domain, username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(domain, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_NTLMUnauthenticatedBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NTLMUnauthenticatedBind'
type MockClient_NTLMUnauthenticatedBind_Call struct {
	*mock.Call
}

// NTLMUnauthenticatedBind is a helper method to define mock.On call
//   - domain string
//   - username string
func (_e *MockClient_Expecter) NTLMUnauthenticatedBind(domain interface{}, username interface{}) *MockClient_NTLMUnauthenticatedBind_Call {
	return &MockClient_NTLMUnauthenticatedBind_Call{Call: _e.mock.On("NTLMUnauthenticatedBind", domain, username)}
}

func (_c *MockClient_NTLMUnauthenticatedBind_Call) Run(run func(domain string, username string)) *MockClient_NTLMUnauthenticatedBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_NTLMUnauthenticatedBind_Call) Return(_a0 error) *MockClient_NTLMUnauthenticatedBind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_NTLMUnauthenticatedBind_Call) RunAndReturn(run func(string, string) error) *MockClient_NTLMUnauthenticatedBind_Call {
	_c.Call.Return(run)
	return _c
}

// PasswordModify provides a mock function with given fields: _a0
func (_m *MockClient) PasswordModify(_a0 *ldap.PasswordModifyRequest) (*ldap.PasswordModifyResult, error) {
	ret := _m.Called(_a0)

	var r0 *ldap.PasswordModifyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.PasswordModifyRequest) (*ldap.PasswordModifyResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ldap.PasswordModifyRequest) *ldap.PasswordModifyResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.PasswordModifyResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.PasswordModifyRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_PasswordModify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasswordModify'
type MockClient_PasswordModify_Call struct {
	*mock.Call
}

// PasswordModify is a helper method to define mock.On call
//   - _a0 *ldap.PasswordModifyRequest
func (_e *MockClient_Expecter) PasswordModify(_a0 interface{}) *MockClient_PasswordModify_Call {
	return &MockClient_PasswordModify_Call{Call: _e.mock.On("PasswordModify", _a0)}
}

func (_c *MockClient_PasswordModify_Call) Run(run func(_a0 *ldap.PasswordModifyRequest)) *MockClient_PasswordModify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.PasswordModifyRequest))
	})
	return _c
}

func (_c *MockClient_PasswordModify_Call) Return(_a0 *ldap.PasswordModifyResult, _a1 error) *MockClient_PasswordModify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_PasswordModify_Call) RunAndReturn(run func(*ldap.PasswordModifyRequest) (*ldap.PasswordModifyResult, error)) *MockClient_PasswordModify_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: _a0
func (_m *MockClient) Search(_a0 *ldap.SearchRequest) (*ldap.SearchResult, error) {
	ret := _m.Called(_a0)

	var r0 *ldap.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest) (*ldap.SearchResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest) *ldap.SearchResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.SearchRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - _a0 *ldap.SearchRequest
func (_e *MockClient_Expecter) Search(_a0 interface{}) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search", _a0)}
}

func (_c *MockClient_Search_Call) Run(run func(_a0 *ldap.SearchRequest)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.SearchRequest))
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(_a0 *ldap.SearchResult, _a1 error) *MockClient_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(*ldap.SearchRequest) (*ldap.SearchResult, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWithPaging provides a mock function with given fields: searchRequest, pagingSize
func (_m *MockClient) SearchWithPaging(searchRequest *ldap.SearchRequest, pagingSize uint32) (*ldap.SearchResult, error) {
	ret := _m.Called(searchRequest, pagingSize)

	var r0 *ldap.SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest, uint32) (*ldap.SearchResult, error)); ok {
		return rf(searchRequest, pagingSize)
	}
	if rf, ok := ret.Get(0).(func(*ldap.SearchRequest, uint32) *ldap.SearchResult); ok {
		r0 = rf(searchRequest, pagingSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.SearchRequest, uint32) error); ok {
		r1 = rf(searchRequest, pagingSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_SearchWithPaging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWithPaging'
type MockClient_SearchWithPaging_Call struct {
	*mock.Call
}

// SearchWithPaging is a helper method to define mock.On call
//   - searchRequest *ldap.SearchRequest
//   - pagingSize uint32
func (_e *MockClient_Expecter) SearchWithPaging(searchRequest interface{}, pagingSize interface{}) *MockClient_SearchWithPaging_Call {
	return &MockClient_SearchWithPaging_Call{Call: _e.mock.On("SearchWithPaging", searchRequest, pagingSize)}
}

func (_c *MockClient_SearchWithPaging_Call) Run(run func(searchRequest *ldap.SearchRequest, pagingSize uint32)) *MockClient_SearchWithPaging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.SearchRequest), args[1].(uint32))
	})
	return _c
}

func (_c *MockClient_SearchWithPaging_Call) Return(_a0 *ldap.SearchResult, _a1 error) *MockClient_SearchWithPaging_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_SearchWithPaging_Call) RunAndReturn(run func(*ldap.SearchRequest, uint32) (*ldap.SearchResult, error)) *MockClient_SearchWithPaging_Call {
	_c.Call.Return(run)
	return _c
}

// SetTimeout provides a mock function with given fields: _a0
func (_m *MockClient) SetTimeout(_a0 time.Duration) {
	_m.Called(_a0)
}

// MockClient_SetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeout'
type MockClient_SetTimeout_Call struct {
	*mock.Call
}

// SetTimeout is a helper method to define mock.On call
//   - _a0 time.Duration
func (_e *MockClient_Expecter) SetTimeout(_a0 interface{}) *MockClient_SetTimeout_Call {
	return &MockClient_SetTimeout_Call{Call: _e.mock.On("SetTimeout", _a0)}
}

func (_c *MockClient_SetTimeout_Call) Run(run func(_a0 time.Duration)) *MockClient_SetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockClient_SetTimeout_Call) Return() *MockClient_SetTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_SetTimeout_Call) RunAndReturn(run func(time.Duration)) *MockClient_SetTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// SimpleBind provides a mock function with given fields: _a0
func (_m *MockClient) SimpleBind(_a0 *ldap.SimpleBindRequest) (*ldap.SimpleBindResult, error) {
	ret := _m.Called(_a0)

	var r0 *ldap.SimpleBindResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*ldap.SimpleBindRequest) (*ldap.SimpleBindResult, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ldap.SimpleBindRequest) *ldap.SimpleBindResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SimpleBindResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*ldap.SimpleBindRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_SimpleBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimpleBind'
type MockClient_SimpleBind_Call struct {
	*mock.Call
}

// SimpleBind is a helper method to define mock.On call
//   - _a0 *ldap.SimpleBindRequest
func (_e *MockClient_Expecter) SimpleBind(_a0 interface{}) *MockClient_SimpleBind_Call {
	return &MockClient_SimpleBind_Call{Call: _e.mock.On("SimpleBind", _a0)}
}

func (_c *MockClient_SimpleBind_Call) Run(run func(_a0 *ldap.SimpleBindRequest)) *MockClient_SimpleBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ldap.SimpleBindRequest))
	})
	return _c
}

func (_c *MockClient_SimpleBind_Call) Return(_a0 *ldap.SimpleBindResult, _a1 error) *MockClient_SimpleBind_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_SimpleBind_Call) RunAndReturn(run func(*ldap.SimpleBindRequest) (*ldap.SimpleBindResult, error)) *MockClient_SimpleBind_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields:
func (_m *MockClient) Start() {
	_m.Called()
}

// MockClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockClient_Expecter) Start() *MockClient_Start_Call {
	return &MockClient_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockClient_Start_Call) Run(run func()) *MockClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Start_Call) Return() *MockClient_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Start_Call) RunAndReturn(run func()) *MockClient_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartTLS provides a mock function with given fields: _a0
func (_m *MockClient) StartTLS(_a0 *tls.Config) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*tls.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_StartTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTLS'
type MockClient_StartTLS_Call struct {
	*mock.Call
}

// StartTLS is a helper method to define mock.On call
//   - _a0 *tls.Config
func (_e *MockClient_Expecter) StartTLS(_a0 interface{}) *MockClient_StartTLS_Call {
	return &MockClient_StartTLS_Call{Call: _e.mock.On("StartTLS", _a0)}
}

func (_c *MockClient_StartTLS_Call) Run(run func(_a0 *tls.Config)) *MockClient_StartTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tls.Config))
	})
	return _c
}

func (_c *MockClient_StartTLS_Call) Return(_a0 error) *MockClient_StartTLS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_StartTLS_Call) RunAndReturn(run func(*tls.Config) error) *MockClient_StartTLS_Call {
	_c.Call.Return(run)
	return _c
}

// TLSConnectionState provides a mock function with given fields:
func (_m *MockClient) TLSConnectionState() (tls.ConnectionState, bool) {
	ret := _m.Called()

	var r0 tls.ConnectionState
	var r1 bool
	if rf, ok := ret.Get(0).(func() (tls.ConnectionState, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() tls.ConnectionState); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tls.ConnectionState)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockClient_TLSConnectionState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TLSConnectionState'
type MockClient_TLSConnectionState_Call struct {
	*mock.Call
}

// TLSConnectionState is a helper method to define mock.On call
func (_e *MockClient_Expecter) TLSConnectionState() *MockClient_TLSConnectionState_Call {
	return &MockClient_TLSConnectionState_Call{Call: _e.mock.On("TLSConnectionState")}
}

func (_c *MockClient_TLSConnectionState_Call) Run(run func()) *MockClient_TLSConnectionState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_TLSConnectionState_Call) Return(_a0 tls.ConnectionState, _a1 bool) *MockClient_TLSConnectionState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_TLSConnectionState_Call) RunAndReturn(run func() (tls.ConnectionState, bool)) *MockClient_TLSConnectionState_Call {
	_c.Call.Return(run)
	return _c
}

// UnauthenticatedBind provides a mock function with given fields: username
func (_m *MockClient) UnauthenticatedBind(username string) error {
	ret := _m.Called(username)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_UnauthenticatedBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnauthenticatedBind'
type MockClient_UnauthenticatedBind_Call struct {
	*mock.Call
}

// UnauthenticatedBind is a helper method to define mock.On call
//   - username string
func (_e *MockClient_Expecter) UnauthenticatedBind(username interface{}) *MockClient_UnauthenticatedBind_Call {
	return &MockClient_UnauthenticatedBind_Call{Call: _e.mock.On("UnauthenticatedBind", username)}
}

func (_c *MockClient_UnauthenticatedBind_Call) Run(run func(username string)) *MockClient_UnauthenticatedBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_UnauthenticatedBind_Call) Return(_a0 error) *MockClient_UnauthenticatedBind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_UnauthenticatedBind_Call) RunAndReturn(run func(string) error) *MockClient_UnauthenticatedBind_Call {
	_c.Call.Return(run)
	return _c
}

// Unbind provides a mock function with given fields:
func (_m *MockClient) Unbind() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Unbind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unbind'
type MockClient_Unbind_Call struct {
	*mock.Call
}

// Unbind is a helper method to define mock.On call
func (_e *MockClient_Expecter) Unbind() *MockClient_Unbind_Call {
	return &MockClient_Unbind_Call{Call: _e.mock.On("Unbind")}
}

func (_c *MockClient_Unbind_Call) Run(run func()) *MockClient_Unbind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Unbind_Call) Return(_a0 error) *MockClient_Unbind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Unbind_Call) RunAndReturn(run func() error) *MockClient_Unbind_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
